google.maps.__gjsload__('map', function(_){'use strict';var qz=function(a,b){return(a.R&&0<_.Qc(b.j,6)?_.Q(b.j,6):_.Q(b.j,0)).slice()},rz=function(a,b){return new _.us(_.Q(a.j,1)[b])},sz=function(a){this.j=a||[]},tz=function(a){this.j=a||[]},uz=function(a,b){for(var c=0,d=_.Qc(a.j.j,1);c<d;c++){var e=rz(a.j,c);0==e.getType()&&(e.j[2]=b)}},vz=function(a){var b=Math.round(1E7*a);return 0>a?b+4294967296:b},wz=function(a,b){for(var c=a.S.j[7],c=qz(a,c?new _.ze(c):_.Oh),d=0;d<c.length;++d)c[d]+="deg="+b+"&";return c},xz=function(a){var b=a.S.j[1];
return qz(a,b?new _.ze(b):_.Nh)},yz=function(a,b){return _.qk(a.get("projection"),b,a.get("zoom"),a.get("offset"),a.get("center"))},zz=function(){var a=_.R;a.j[1]=a.j[1]||[];return new _.Be(a.j[1])},Az=function(a){a=a.j[14];return null!=a?a:0},Bz=function(a,b){return new sz(_.Q(a.j,4)[b])},Cz=function(a,b){return _.Q(a.j,5)[b]},Dz=function(a){return(a=a.j[1])?new _.ye(a):_.Mh},Ez=function(a){return(a=a.j[0])?new _.ye(a):_.Lh},Fz=function(a){a=a.j[1];return null!=a?a:0},Gz=function(a){a=a.j[0];return null!=
a?a:0},Hz=function(a){this.j=a||[]},Iz=function(a,b){for(var c=a.length,d=_.va(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0},Jz=function(a,b){for(var c=0,d=a.R,e=a.j,f=0,g;g=b[f++];)if(a.intersects(g)){var h=g.R,k=g.j,n=0;if(_.Yi(g,a))return 1;n=e.contains(k.j)&&k.contains(e.j)&&!_.gd(e,k)?_.hd(k.j,e.R)+_.hd(e.j,k.R):_.hd(e.contains(k.j)?k.j:e.j,e.contains(k.R)?k.R:e.R);c+=n*(Math.min(d.j,h.j)-Math.max(d.R,h.R))}return c/=_.jd(d)*_.fd(e)},Kz=function(a,b){var c=
a.x,d=a.y;switch(b){case 90:a.x=d;a.y=256-c;break;case 180:a.x=256-c;a.y=256-d;break;case 270:a.x=256-d,a.y=c}},Lz=function(a,b,c,d,e,f,g,h,k){this.Pa=a.Pa;this.zoom=a.zoom;this.j=a;this.W=b;this.ua=c;this.Ba=d;this.ma=e;this.V=f;this.qa=g;this.U=h;this.S=_.Fk(k)?k:null;this.R="";this.tc()},Mz=function(a,b,c,d,e){this.Pa=a;this.zoom=b;this.R=c;this.j=d.slice(0);this.S=e&&e.Ph||_.ta},Nz=function(){this.maxZoom=this.minZoom=-1;this.j=[];this.ab=[]},Oz=function(a){this.S=a;this.j=null;this.set("idle",
!0)},Pz=function(){var a=!1;return function(b,c){if(b&&c){if(.999999>Jz(b,c))return a=!1;var d=_.pk(b,(_.Py-1)/2);return.999999<Jz(d,c)?a=!0:a}}},Qz=function(){return function(a,b){return a&&b?.9<=Jz(a,b):void 0}},Rz=_.na("j"),Wz=function(a){for(var b=[],c=0;c<_.x(a);++c){var d,e=a[c].elementType;d=a[c].stylers;var f=[],g;g=(g=a[c].featureType)&&Sz[g.toLowerCase()];(g=null!=g?g:null)&&f.push("s.t:"+g);(e=e&&Tz[e.toLowerCase()]||null)&&f.push("s.e:"+e);for(e=0;e<_.x(d);++e){a:{g=d[e];var h=void 0;
for(h in g){var k=g[h],n=h&&Uz[h.toLowerCase()]||null;if(n&&(_.E(k)||_.Sa(k)||_.Ta(k))&&k){"color"==h&&Vz.test(k)&&(k="#ff"+k.substr(1));g="p."+n+":"+k;break a}}g=void 0}g&&f.push(g)}(d=f.join("|"))&&b.push(d)}a=b.join(",");return 1E3>=a.length?a:""},Xz=_.na("R"),Yz=function(a,b){var c=a.V,d=a.R.get(b);c&&c instanceof _.Zv&&c.j&&(c.j.unbindAll(),a.unbind("mapType"));d&&d instanceof _.Zv&&d.j?(c=d.j,c.bindTo("heading",a),c.bindTo("tilt",a),a.bindTo("mapType",c)):a.set("mapType",d)},aA=function(a,b,
c){var d=this;this.S=a;this.R=b;this.ma=c;_.H.bind(b,"insert_at",d,d.U);_.H.bind(b,"remove_at",d,d.V);_.H.bind(b,"set_at",d,d.W);this.j=[];d.R.forEach(function(a){a=Zz(d,a);d.j.push(a)});$z(d)},$z=function(a){_.G(a.j,function(a,c){a.set("zIndex",c)})},Zz=function(a,b){if(b){var c;switch(b.wb){case "roadmap":c="Otm";break;case "satellite":c="Otk";break;case "hybrid":c="Oth";break;case "terrain":c="Otr";break;default:c=b instanceof _.ig?"Ots":"Oto"}a.ma(c)}c=new _.dw(a.S,null);c.bindTo("size",a);c.bindTo("zoom",
a);c.bindTo("offset",a);c.bindTo("projectionBounds",a);c.set("mapType",b);c.listener=b&&_.H.forward(c,"tilesloaded",b);return c},bA=function(a){a.release();a.listener&&(_.H.removeListener(a.listener),delete a.listener)},cA=function(a,b,c,d){function e(){if(!g.j&&!g.R){var n=c.get(),p=b.get("center"),q=b.get("zoom");null!=q&&p&&n&&n.width&&n.height&&(c.removeListener(e),h.remove(),k.remove(),d.size=n.width+"x"+n.height,d.hadviewport=f,g.R=p,g.V=q,g.j=_.Mf("map2",{startTime:f?a:void 0,oq:d}))}}this.va=
b;this.S={};this.V=this.R=this.j=null;this.U=!1;var f=!0,g=this,h=b.addListener("center_changed",e),k=b.addListener("zoom_changed",e);c.addListener(e);e();f=!1},dA=function(a,b,c){!a.j||a.S[b]||a.U||(a.R.j(a.va.get("center"))&&a.V==a.va.get("zoom")?(a.S[b]=!0,c.call(a)):a.U=!0)},eA=function(a,b){dA(a,"staticmap",function(){var a={staticmap:b};dA(this,"firstpixel",function(){a.firstpixel=b});dA(this,"allpixels",function(){a.allpixels=b});_.Kf(this.j,a)})},gA=function(a){var b={};b.firstmap=fA;b.hdpi=
1<_.wf();b.mob=!_.W.W;b.staticmap=a;return b},hA=function(a,b){this.S=a;this.U=b},iA=function(a,b){var c=window.document.createElement("div");_.el(c);_.jl(c,0);b(c);a.appendChild(c);this.set("div",c)},vA=function(a,b){this.j=function(c,d,e,f,g){var h;a:{if(!(7>d)){var k=1<<d-7;h=c.x/k;for(var k=c.y/k,n=0;n<jA.length;++n)if(h>=jA[n].Ag&&h<=jA[n].zg&&k>=jA[n].Cg&&k<=jA[n].Bg){h=!0;break a}}h=!1}return h?b.j(c,d,e,f,g):a.j(c,d,e,f,g)}},wA=function(a,b){this.S=b||new _.pf;this.j=new _.bd(a%360,45);this.U=
new _.M(0,0);this.R=!0},xA=function(a,b,c,d,e,f){this.j=function(g,h,k,n,p){return new Lz(_.Jv(g,h,k,n,p),a,_.Xf,b,c,d,e,k.width,f)}},yA=function(a){this.j=function(b,c,d,e,f){function g(){f&&f.ad&&k.Jc()&&f.ad()}var h=_.Bk(a,function(a,h){return a.j(b,c,d,e,{nh:f&&f.nh,ad:g,zIndex:h})}),k=new Mz(b,c,e,h,{Ph:f&&f.Ph});return k}},AA=function(a,b){this.R=b;this.j=360/b.length;this.S=a;zA(this)},zA=function(a){var b=a.get("heading")||0,c=a.S,d=a.get("tilt");d?c=a.R[b/a.j]:0==d&&0!=b&&a.set("heading",
0);c!=a.get("mapType")&&a.set("mapType",c)},BA=function(a,b,c,d){this.j=[];for(var e=0;e<_.x(a);++e){var f=a[e],g=new Nz,h=f.j[2];g.minZoom=(null!=h?h:0)||0;h=f.j[3];g.maxZoom=(null!=h?h:0)||d;for(h=0;h<_.Qc(f.j,5);++h)g.j.push(Cz(f,h));for(h=0;h<_.Qc(f.j,4);++h){var k=_.Rj(b,new _.kd(new _.K(Gz(Ez(Bz(f,h)))/1E7,Fz(Ez(Bz(f,h)))/1E7),new _.K(Gz(Dz(Bz(f,h)))/1E7,Fz(Dz(Bz(f,h)))/1E7)),g.maxZoom);g.ab[h]=new _.qf([new _.M(Math.floor(k.ya/c.width),Math.floor(k.wa/c.height)),new _.M(Math.floor(k.Ca/c.width),
Math.floor(k.Da/c.height))])}this.j.push(g)}},CA=function(){var a=new Rz(Qz()),b={};b.obliques=new Rz(Pz());b.report_map_issue=a;return b},DA=function(a,b){var c=a.__gm,d=new aA(b,a.overlayMapTypes,_.Ek(_.em,a));d.bindTo("size",c);d.bindTo("zoom",c);d.bindTo("offset",c);d.bindTo("projectionBounds",c)},EA=function(a){var b=new Oz(300);b.bindTo("input",a,"bounds");_.H.addListener(b,"idle_changed",function(){b.get("idle")&&_.H.trigger(a,"idle")})},FA=function(a){if(a&&_.$k(a.getDiv())&&(_.Qk()||_.Pk())){_.em(a,
"Tdev");var b=window.document.querySelector('meta[name="viewport"]');(b=b&&b.content)&&b.match(/width=device-width/)&&_.em(a,"Mfp")}},GA=function(a,b){function c(){var c=b.get("mapType");if(c)switch(c.wb){case "roadmap":_.em(a,"Tm");break;case "satellite":c.qa&&_.em(a,"Ta");_.em(a,"Tk");break;case "hybrid":c.qa&&_.em(a,"Ta");_.em(a,"Th");break;case "terrain":_.em(a,"Tr");break;default:_.em(a,"To")}}c();_.H.addListener(b,"maptype_changed",c)},HA=function(a){var b=new Xz(a.mapTypes);b.bindTo("bounds",
a);b.bindTo("heading",a);b.bindTo("mapTypeId",a);b.bindTo("tilt",a.__gm);return b},JA=function(a,b){_.Fa(_.ug,function(c,d){b.set(d,IA(a,d))})},KA=function(a,b){this.j=a;this.R=b},LA=_.l(),MA=function(a,b){function c(c){c=b.getAt(c);if(c instanceof _.ig){var e=new _.J,f=c.get("styles");e.set("apistyle",Wz(f));e=IA(a,c.j,e);c.Lf=(0,_.u)(e.Lf,e)}}_.H.addListener(b,"insert_at",c);_.H.addListener(b,"set_at",c);b.forEach(function(a,b){c(b)})},OA=function(a){var b;b=(b=window.navigator.connection||window.navigator.mozConnection||
window.navigator.webkitConnection||null)&&b.type;_.em(a,"Nt",b&&NA[b]||"-na")},PA=function(a,b,c){if((_.Qk()||_.Pk())&&_.sl()){_.em(b,"Mmni");var d=window.setInterval(function(){var e;e=a.j.getBoundingClientRect();if(e=!(0>=e.top-5&&0>=e.left-5&&e.height+5>=window.document.body.scrollHeight&&e.width+5>=window.document.body.scrollWidth))e=a.j.getBoundingClientRect(),e=0>=e.top-5&&0>=e.left-5&&e.bottom+5>=window.innerHeight&&e.right+5>=window.innerWidth&&(!c||c());e&&(_.em(b,"Mmus"),window.clearInterval(d))},
1E3)}},QA=_.na("j"),RA=function(a){this.j=a;_.H.bind(this.j,"set_at",this,this.R);_.H.bind(this.j,"insert_at",this,this.R);this.R()},SA=function(a){var b=[];a.j&&a.j.forEach(function(a){a&&b.push(a)});return b.join(", ")},TA=function(){var a,b=new _.J;b.bounds_changed=function(){var c=b.get("bounds");c?a&&_.Ai(a,c)||(a=_.rf(c.ya-512,c.wa-512,c.Ca+512,c.Da+512),b.set("boundsQ",a)):b.set("boundsQ",c)};return b},UA=function(){this.W=new _.nf;this.U={};this.S={}},VA=_.l(),XA=function(){WA(this)},WA=function(a){var b=
new _.Av(a.get("minZoom")||0,a.get("maxZoom")||30),c=a.get("mapTypeMinZoom"),d=a.get("mapTypeMaxZoom"),e=a.get("trackerMaxZoom");_.E(c)&&(b.min=Math.max(b.min,c));_.E(e)?b.max=Math.min(b.max,e):_.E(d)&&(b.max=Math.min(b.max,d));a.set("zoomRange",b)},YA=_.l(),ZA=function(a,b,c,d,e,f,g){var h=c.__gm,k=new _.qx(c,a,b,!!c.Ka,e,h,d,g,(0,_.u)(f.j,f));k.bindTo("draggingCursor",c);k.bindTo("draggableMap",c,"draggable");_.H.addListener(c,"zoom_changed",function(){k.get("zoom")!=c.get("zoom")&&k.set("zoom",
c.get("zoom"))});k.set("zoom",c.get("zoom"));k.bindTo("disablePanMomentum",c);k.bindTo("projectionTopLeft",e);k.bindTo("draggableCursor",h,"cursor");d.bindTo("zoom",k);e.bindTo("zoom",k);return k},$A=function(a,b,c,d){var e=new cA(a,b,c,gA(!!d));fA=!1;d&&_.Zi(d,function g(a){a&&(d.removeListener(g),eA(e,a))});_.H.addListenerOnce(b,"tilesloaded",(0,_.u)(e.ma,e));return e},aB=function(a,b,c,d){return d?new hA(a,function(){return b}):_.T[23]?new hA(a,function(a){var d=c.get("scale");return 2==d||4==
d?b:a}):a},bB=function(a,b){var c=a.__gm,d=new iA(b,(0,_.u)(_.kl.R,_.kl));d.bindTo("center",a);d.bindTo("projectionBounds",c);d.bindTo("offset",c);return d},cB=_.na("j"),dB=function(a,b,c){var d=_.Di(),e=_.Pe(_.R);this.va=b;this.j=c;this.R=new _.pf;this.S=_.Ne(e);this.U=_.Oe(e);this.W=Az(d);this.V=_.Hi(d);this.ma=new _.Ev(a,d,e);b={};c=0;for(d=_.Qc(a.j,5);c<d;++c){var e=c,e=new Hz(_.Q(a.j,5)[e]),f;f=e.j[1];f=null!=f?f:0;b[f]=b[f]||[];b[f].push(e)}this.qa=new BA(b[1],this.R,new _.N(256,256),22);a.j[1]=
a.j[1]||[];a.j[7]=a.j[7]||[]},eB=function(a,b,c,d){var e=d||{},f=_.E(e.heading),g=c?function(a,b){return c.V(a,b,e.bl)}:_.oa(0);d=("hybrid"==b&&!f||"terrain"==b||"roadmap"==b)&&0!=e.$i;var h=e.wd||_.oa(null);return"satellite"==b?(f?(b=wz(a.ma,e.heading),a=null):(b=xz(a.ma),a=a.qa),new _.Ov(b,a,d&&1<_.wf(),_.$v(e.heading),h)):new xA(_.Fv(a.ma),d&&1<_.wf(),_.$v(e.heading,!!e.bl),g,h,e.heading)},gB=function(a){function b(a,b){if(!b||!b.Lc)return b;var c=[];_.vi(c,b.Lc.j);c=new _.jt(c);_.Xs(_.Au(c)).j[0]=
a;return{scale:b.scale,Od:b.Od,Lc:c}}var c,d=eB(a,"roadmap",a.j,{$i:!1,wd:function(){return b(3,c.get("options"))}}),e=eB(a,"roadmap",a.j,{wd:function(){return b(18,c.get("options"))}}),d=new yA([d,e]),e=eB(a,"roadmap",a.j,{wd:function(){return c.get("options")}});c=new _.Zv(new vA(d,e),a.R,21,"Mapa","Mostrar mapa de ruas","Sentimos muito, mas n\u00e3o temos imagens daqui.",_.jy.roadmap,!1,"m@"+a.W,47,"roadmap",a.V,a.S,a.U);fB(a,c);return c},hB=function(a,b){function c(){return g.get("options")}var d=
_.E(b),e=eB(a,"satellite",null,{heading:b,wd:c}),f=eB(a,"hybrid",a.j,{heading:b,wd:c}),g=new _.Zv(new yA([e,f]),_.E(b)?new wA(b):a.R,d?21:22,"H\u00edbrido","Mostrar imagens com nomes de rua","Sentimos muito, mas n\u00e3o temos imagens daqui.",_.jy.hybrid,d,"m@"+a.W,50,"hybrid",a.V,a.S,a.U);fB(a,g);return g},iB=function(a,b){var c=_.E(b),d=eB(a,"satellite",null,{heading:b,wd:function(){return e.get("options")}}),e=new _.Zv(d,_.E(b)?new wA(b):a.R,c?21:22,"Sat\u00e9lite","Mostrar imagens de sat\u00e9lite",
"Sentimos muito, mas n\u00e3o temos imagens daqui.",c?"a":_.jy.satellite,c,null,null,"satellite",a.V,a.S,a.U);return e},IA=function(a,b,c){var d=null,e=[0,90,180,270],f=_.ve();if("hybrid"==b){d=hB(a);b=[];c=0;for(f=e.length;c<f;++c)b.push(hB(a,e[c]));d.j=new AA(d,b)}else if("satellite"==b){d=iB(a);b=[];c=0;for(f=e.length;c<f;++c)b.push(iB(a,e[c]));d.j=new AA(d,b)}else"roadmap"==b&&1<_.wf()&&+_.Pi(f)?d=gB(a):(e=eB(a,b,a.j,{wd:function(){return d.get("options")},bl:!!+_.Oi(f),$i:!+_.Ni(f)}),d="terrain"==
b?new _.Zv(e,a.R,21,"Relevo","Mostrar mapa de ruas com relevo","Sentimos muito, mas n\u00e3o temos imagens daqui.",_.jy.terrain,!1,"r@"+a.W,63,"terrain",a.V,a.S,a.U,+_.Oi(f)?new _.N(128,128):new _.N(256,256)):new _.Zv(e,a.R,21,"Mapa","Mostrar mapa de ruas","Sentimos muito, mas n\u00e3o temos imagens daqui.",_.jy.roadmap,!1,"m@"+a.W,47,"roadmap",a.V,a.S,a.U,+_.Oi(f)?new _.N(128,128):new _.N(256,256)),fB(a,d,c));return d},fB=function(a,b,c){var d=a.va.__gm;c?b.bindTo("apistyle",c):(b.bindTo("layers",
d,"layers"),b.bindTo("apistyle",d),b.bindTo("mapMaker",a.va));b.bindTo("authUser",d);_.T[23]&&b.bindTo("scale",a.va);a.j.R().addListener(function(){b.notify("epochs")})},jB=_.l();sz.prototype.$=_.m("j");_.nf.prototype.j=_.zi(7,function(a){this.Ea.forEach(function(b){b(a)})});tz.prototype.$=_.m("j");tz.prototype.getTile=function(){var a=this.j[1];return a?new _.Ys(a):_.Oy};Hz.prototype.$=_.m("j");Hz.prototype.clearRect=function(){var a=this.j;4 in a&&delete a[4]};
var Uz={hue:"h",saturation:"s",lightness:"l",gamma:"g",invert_lightness:"il",visibility:"v",color:"c",weight:"w"},Vz=/^#[0-9a-fA-F]{6}$/,Sz={all:0,administrative:1,"administrative.country":17,"administrative.province":18,"administrative.locality":19,"administrative.neighborhood":20,"administrative.land_parcel":21,poi:2,"poi.business":33,"poi.government":34,"poi.school":35,"poi.medical":36,"poi.attraction":37,"poi.place_of_worship":38,"poi.sports_complex":39,"poi.park":40,road:3,"road.highway":49,
"road.highway.controlled_access":785,"road.arterial":50,"road.local":51,transit:4,"transit.line":65,"transit.station":66,"transit.station.rail":1057,"transit.station.bus":1058,"transit.station.airport":1059,"transit.station.ferry":1060,landscape:5,"landscape.man_made":81,"landscape.natural":82,"landscape.natural.landcover":1313,"landscape.natural.terrain":1314,water:6},Tz={all:"",geometry:"g","geometry.fill":"g.f","geometry.stroke":"g.s",labels:"l","labels.icon":"l.i","labels.text":"l.t","labels.text.fill":"l.t.f",
"labels.text.stroke":"l.t.s"},jA=[{Ag:108.25,zg:109.625,Cg:49,Bg:51.5},{Ag:109.625,zg:109.75,Cg:49,Bg:50.875},{Ag:109.75,zg:110.5,Cg:49,Bg:50.625},{Ag:110.5,zg:110.625,Cg:49,Bg:49.75}],fA=!0;_.t=Lz.prototype;_.t.Bb=function(){return this.j.Bb()};_.t.Jc=function(){return this.j.Jc()};_.t.release=function(){this.j.release()};_.t.Bc=function(){this.j.Bc()};
_.t.tc=function(){var a=this.qa();if(a&&a.Lc){var b=this.ma(new _.M(this.Pa.x,this.Pa.y),this.zoom);if(b){for(var c=2==a.scale||4==a.scale?a.scale:1,c=Math.min(1<<this.zoom,c),d=this.Ba&&4!=c,e=this.zoom,f=c;1<f;f/=2)e--;var f=this.U,g;1!=c&&(f/=c);d&&(c*=2);1!=c&&(g=c);c=new _.Qv(a.Lc);_.Sv(c,0);g&&(_.Bu(c.j).j[4]=g);_.Tv(c,b,e,f);if(e=this.V(b,this.zoom,128==this.U))uz(c,e),_.Fk(this.S)&&_.Yv(c,this.S),e=this.W,b=e[(b.x+2*b.y)%e.length],b+="pb="+_.Pv(_.zu(c.j)),null!=a.Od&&(b+="&authuser="+a.Od),
b=this.ua(b),this.R==b?this.j.tc():(this.R=b,this.j.setUrl(b))}else this.R="",this.j.setUrl("")}};_.t=Mz.prototype;_.t.Bb=_.m("R");_.t.Jc=function(){return Iz(this.j,function(a){return a.Jc()})};_.t.release=function(){_.ec(this.j,function(a){a.release()});this.S()};_.t.Bc=function(){_.ec(this.j,function(a){a.Bc()})};_.t.tc=function(){_.ec(this.j,function(a){a.tc()})};var NA={bluetooth:"-b",cellular:"-c",ethernet:"-e",none:"-n",wifi:"-wf",wimax:"-wm",other:"-o"};_.w(Oz,_.J);
Oz.prototype.input_changed=function(){this.get("idle")&&this.set("idle",!1);this.j&&window.clearTimeout(this.j);this.j=window.setTimeout((0,_.u)(this.R,this),this.S)};Oz.prototype.R=function(){this.j=null;this.set("idle",!0)};_.w(Rz,_.J);Rz.prototype.changed=function(a){if("available"!=a){a=this.get("viewport");var b=this.get("featureRects");a=this.j(a,b);null!=a&&a!=this.get("available")&&this.set("available",a)}};_.w(Xz,_.J);
Xz.prototype.mapTypeId_changed=function(){var a=this.get("mapTypeId");this.S(a)};Xz.prototype.setMapTypeId=function(a){this.S(a);this.set("mapTypeId",a)};
Xz.prototype.S=function(a){var b=this.R.get(a);if(!b||b!=this.V){this.U&&(_.H.removeListener(this.U),this.U=null);var c=(0,_.u)(this.S,this,a);a&&(this.U=_.H.addListener(this.R,a.toLowerCase()+"_changed",c));b&&b instanceof _.ig?(a=b.j,this.set("styles",b.get("styles"))):this.set("styles",null);Yz(this,a);this.j&&this.j.unbindAll();this.j=new _.aw(["mapType"],"maxZoom",function(a){return(a=a||b)&&a.maxZoom});b&&b instanceof _.Zv&&b.j&&this.j.bindTo("mapType",b.j);this.bindTo("maxZoom",this.j);this.set("minZoom",
b&&b.minZoom);this.V=b}};_.w(aA,_.J);aA.prototype.U=function(a){var b=this.j,c=Zz(this,this.R.getAt(a));b.splice(a,0,c);$z(this)};aA.prototype.V=function(a){var b=this.j;bA(b[a]);b.splice(a,1);$z(this)};aA.prototype.W=function(a){bA(this.j[a]);var b=Zz(this,this.R.getAt(a));b.set("zIndex",a);this.j[a]=b};cA.prototype.qa=function(){dA(this,"visreq",function(){_.Lf(this.j,"visreq")})};cA.prototype.ua=function(){dA(this,"visres",function(){_.Lf(this.j,"visres")})};
cA.prototype.W=function(){dA(this,"firsttile",function(){var a={firsttile:void 0};dA(this,"firstpixel",function(){a.firstpixel=void 0});_.Kf(this.j,a)})};cA.prototype.ma=function(){dA(this,"tilesloaded",function(){var a={tilesloaded:void 0};dA(this,"allpixels",function(){a.allpixels=void 0});_.Kf(this.j,a)})};hA.prototype.V=function(a,b,c){return this.U(this.S.V(a,b,c))};hA.prototype.j=function(a){return this.U(this.S.j(a))};hA.prototype.R=function(){return this.S.R()};_.w(iA,_.J);
iA.prototype.offset_changed=function(){this.set("newCenter",this.get("center"));var a=this.get("projectionBounds"),b=this.get("offset");if(a&&b){var c=this.get("div");_.al(c,new _.M(a.ya-b.width,a.wa-b.height));_.fl(c)}};wA.prototype.fromLatLngToPoint=function(a,b){var c=this.S.fromLatLngToPoint(a,b);Kz(c,this.j.heading());c.y=(c.y-128)/_.Ny+128;return c};
wA.prototype.fromPointToLatLng=function(a,b){var c=this.U;c.x=a.x;c.y=(a.y-128)*_.Ny+128;Kz(c,360-this.j.heading());return this.S.fromPointToLatLng(c,b)};wA.prototype.getPov=_.m("j");_.w(AA,_.J);AA.prototype.heading_changed=function(){var a=this.get("heading");if(_.E(a)){var b;b=_.Ja(a,0,360);b=this.j*Math.round(b/this.j);a!==b?this.set("heading",b):zA(this)}};AA.prototype.tilt_changed=function(){zA(this)};
BA.prototype.R=function(a,b){for(var c=this.j,d=new _.M(a.x%(1<<b),a.y),e=0;e<c.length;++e){var f=c[e];if(!(f.minZoom>b||f.maxZoom<b)){var g=_.x(f.ab);if(0==g)return f.j;for(var h=f.maxZoom-b,k=0;k<g;++k){var n=f.ab[k];if(_.Bi(new _.qf([new _.M(n.ya>>h,n.wa>>h),new _.M(1+(n.Ca>>h),1+(n.Da>>h))]),d))return f.j}}}return null};_.w(KA,_.J);
KA.prototype.getPrintableImageUri=function(a,b,c,d,e){var f=this.get("mapType");if(2048<a*(e||1)||2048<b*(e||1)||!(f instanceof _.Zv))return null;var g=d||this.get("zoom");if(null==g)return null;var h=c||this.get("center");if(!h)return null;c=f.get("options");if(!c.Lc)return null;d=new _.Qv(c.Lc);_.Sv(d,0);var k=this.R.j(g);k&&uz(d,k);if("hybrid"==f.wb){_.Du(d.j);for(f=_.Qc(d.j.j,1)-1;0<f;--f){var k=rz(d.j,f),n=rz(d.j,f-1);_.vi(k.j,n?n.$():null)}f=rz(d.j,0);f.j[0]=1;1 in f.j&&delete f.j[1];2 in f.j&&
delete f.j[2]}if(2==e||4==e)_.Bu(d.j).j[4]=e;e=_.Cu(d.j);e.j[3]=e.j[3]||[];e=new _.ft(e.j[3]);e.setZoom(g);e.j[2]=e.j[2]||[];g=new _.Cn(e.j[2]);f=vz(h.lat());g.j[0]=f;h=vz(h.lng());g.j[1]=h;e.j[0]=e.j[0]||[];h=new _.gt(e.j[0]);h.j[0]=a;h.j[1]=b;a=this.j;a+="pb="+_.Pv(_.zu(d.j));null!=c.Od&&(a+="&authuser="+c.Od);return a};_.w(LA,_.J);LA.prototype.changed=function(a){"mapType"!=a&&"style"!=a&&this.notify("style")};
LA.prototype.getStyle=function(){var a=[],b,c=this.get("mapType");c instanceof _.Zv&&c.R&&(b=new _.tk,b.j[0]=c.R,a.push(b));b=new _.tk;b.j[0]=37;_.uk(b).j[0]="smartmaps";a.push(b);this.get("mapMaker")&&(b=new _.tk,b.j[0]=33,a.push(b));b=this.get("layers");for(var d in b)c=b[d],c.V&&a.push(c.V);return a};_.w(RA,_.J);RA.prototype.R=function(){var a=SA(this);this.get("attributionText")!=a&&this.set("attributionText",a)};
UA.prototype.ma=function(a){if(_.Qc(a.j,0)){this.U={};this.S={};for(var b=0;b<_.Qc(a.j,0);++b){var c,d=b;c=new tz(_.Q(a.j,0)[d]);var e=c.getTile(),d=e.getZoom(),f;f=e.j[1];f=null!=f?f:0;e=e.j[2];e=null!=e?e:0;c=c.j[2];c=null!=c?c:0;var g=this.U;g[d]=g[d]||{};g[d][f]=g[d][f]||{};g[d][f][e]=c;this.S[d]=Math.max(this.S[d]||0,c)}this.W.j(null)}};UA.prototype.V=function(a,b,c){var d=this.U,e=a.x;a=a.y;c&&(e=Math.floor(e/2),a=Math.floor(a/2));return d[b]&&d[b][e]&&d[b][e][a]||0};
UA.prototype.j=function(a){return this.S[a]||0};UA.prototype.R=_.m("W");_.w(VA,_.J);VA.prototype.changed=function(a){if("apistyle"!=a){var b=this.get("mapTypeStyles")||this.get("styles"),c=[];_.T[13]&&c.push({featureType:"poi.business",elementType:"labels",stylers:[{visibility:"off"}]});_.Pa(c,b);this.j=Wz(c);"styles"==a&&this.notify("apistyle")}};VA.prototype.getApistyle=_.m("j");_.w(XA,_.J);XA.prototype.changed=function(a){"zoomRange"!=a&&WA(this)};_.w(YA,_.J);
YA.prototype.changed=function(a){if("maxZoomRects"==a||"latLng"==a){a=this.get("latLng");var b=this.get("maxZoomRects");if(a&&b){for(var c=void 0,d=0,e;e=b[d++];)e.ab.contains(a)&&(c=Math.max(c||0,e.maxZoom));a=c;a!=this.get("maxZoom")&&this.set("maxZoom",a)}else this.set("maxZoom",void 0)}};_.w(cB,_.J);cB.prototype.immutable_changed=function(){var a=this,b=a.get("immutable"),c=a.R;b!=c&&(_.Fa(a.j,function(d){(c&&c[d])!==(b&&b[d])&&a.set(d,b&&b[d])}),a.R=b)};jB.prototype.R=function(a,b,c,d,e,f){function g(){var b=a.get("streetView");b?(a.bindTo("svClient",b,"client"),b.__gm.bindTo("fontLoaded",pa)):(a.unbind("svClient"),a.set("svClient",null))}var h=_.Ne(_.Pe(_.R)),k=a.__gm,n=a.getDiv();_.H.addDomListenerOnce(n,"mousedown",function(){_.em(a,"Mi")},!0);var p=new _.cy(n,b,{qj:!0,Qj:_.Gi(_.Pe(_.R))}),q=p.S;_.jl(p.j,0);_.H.forward(a,"resize",n);k.set("panes",p.U);k.set("innerContainer",p.R);var r=$A(e,a,new _.bw(p,"size"),c&&c.S),v=new YA,y=CA(),z,A;(function(){var c=
Az(_.Di()),d=a.get("noPerTile")&&_.T[15],e=new UA;z=aB(e,c,a,d);A=new _.Px(h,v,y,k.Ba,d?null:e,b.Ka,r)})();A.bindTo("tilt",a);A.bindTo("heading",a);A.bindTo("bounds",a);A.bindTo("zoom",a);A.bindTo("mapMaker",a);A.bindTo("size",k);e=new dB(zz(),a,z);JA(e,a.mapTypes);_.gk()&&_.Wk()||_.L("onion",function(b){b.R(a,z)});var D=new _.Ww(q,p.W,r);e=new _.aw(["blockingLayerCount","staticMapLoading"],"waitWithTiles",function(a,b){return!!a||!!b});_.ak(k.Aa,"sm-block")&&c&&e.bindTo("staticMapLoading",c,"loading");
e.bindTo("blockingLayerCount",k);D.bindTo("waitWithTiles",e);D.set("panes",p.U);D.bindTo("styles",a);_.T[20]&&D.bindTo("animatedZoom",a);_.T[35]&&(_.dy(a),_.ey(a));var C=new _.sx;C.bindTo("tilt",a);C.bindTo("zoom",a);C.bindTo("mapTypeId",a);C.bindTo("aerial",y.obliques,"available");k.bindTo("tilt",C);var F=HA(a);A.bindTo("mapType",F);var I=new RA(k.Ba);_.H.addListener(I,"attributiontext_changed",function(){a.set("mapDataProviders",I.get("attributionText"))});e=new VA;e.bindTo("styles",a);e.bindTo("mapTypeStyles",
F,"styles");k.bindTo("apistyle",e);e=new LA;e.bindTo("mapMaker",a);e.bindTo("mapType",F);e.bindTo("layers",k);k.bindTo("style",e);var P=new _.yw;k.set("projectionController",P);D.bindTo("size",p);D.bindTo("projection",P);D.bindTo("projectionBounds",P);D.bindTo("mapType",F);P.bindTo("projectionTopLeft",D);P.bindTo("offset",D);P.bindTo("latLngCenter",a,"center");P.bindTo("size",p);P.bindTo("projection",a);D.bindTo("fixedPoint",P);a.bindTo("bounds",P,"latLngBounds",!0);k.set("mouseEventTarget",{});e=
new _.nx(_.W.S,p.R);e.bindTo("title",k);var V=ZA(p.R,q,a,D,P,f,e);c&&(f=bB(a,q),c.bindTo("div",f),c.bindTo("center",f,"newCenter"),c.bindTo("zoom",V),c.bindTo("tilt",k),c.bindTo("size",k));k.bindTo("zoom",V);k.bindTo("center",a);k.bindTo("size",p);k.bindTo("mapType",F);k.bindTo("offset",D);k.bindTo("layoutPixelBounds",D);k.bindTo("pixelBounds",D);k.bindTo("projectionTopLeft",D);k.bindTo("projectionBounds",D,"viewProjectionBounds");k.bindTo("projectionCenterQ",P);a.set("tosUrl",_.vy);c=TA();c.bindTo("bounds",
D,"pixelBounds");k.bindTo("pixelBoundsQ",c,"boundsQ");c=new cB({projection:1});c.bindTo("immutable",k,"mapType");f=new _.xw({projection:new _.pf});f.bindTo("projection",c);a.bindTo("projection",f);_.H.forward(k,"panby",D);_.H.forward(k,"panbynow",D);_.H.forward(k,"panbyfraction",D);_.H.addListener(k,"panto",function(b){if(b instanceof _.K)if(a.get("center")){b=P.fromLatLngToDivPixel(b);var c=P.get("offset")||_.Bg;b.x+=Math.round(c.width)-c.width;b.y+=Math.round(c.height)-c.height;_.H.trigger(D,"panto",
b.x,b.y)}else a.set("center",b);else throw Error("panTo: latLng must be of type LatLng");});_.H.forward(k,"pantobounds",D);_.H.addListener(k,"pantolatlngbounds",function(a){if(a instanceof _.kd)_.H.trigger(D,"pantobounds",yz(P,a));else throw Error("panToBounds: latLngBounds must be of type LatLngBounds");});_.H.addListener(V,"zoom_changed",function(){V.get("zoom")!=a.get("zoom")&&(a.set("zoom",V.get("zoom")),_.jm(a,"Mm"))});var X=new XA;X.bindTo("mapTypeMaxZoom",F,"maxZoom");X.bindTo("mapTypeMinZoom",
F,"minZoom");X.bindTo("maxZoom",a);X.bindTo("minZoom",a);X.bindTo("trackerMaxZoom",v,"maxZoom");V.bindTo("zoomRange",X);D.bindTo("zoomRange",X);V.bindTo("draggable",a);V.bindTo("scrollwheel",a);V.bindTo("disableDoubleClickZoom",a);var pa=new _.$x(_.$k(n));k.bindTo("fontLoaded",pa);c=k.R;c.bindTo("scrollwheel",a);c.bindTo("disableDoubleClickZoom",a);g();_.H.addListener(a,"streetview_changed",g);if(!b.Ka){var fb=function(){_.L("controls",function(b){var c=new b.Ei(p.j);k.set("layoutManager",c);D.bindTo("layoutBounds",
c,"bounds");b.gp(c,a,F,p.j,I,y.report_map_issue,X,C,P,p.V,z);b.hp(a,p.R);(c=a.getDiv())&&b.Mk(c)})};if(_.gk()){var gb=_.Iu.Uc().j;c=new _.Zx;c.bindTo("layers",k);c.bindTo("gid",gb);c.bindTo("persistenceKey",gb);_.em(a,"Sm");c=function(){gb.get("gid")&&_.em(a,"Su")};c();_.H.addListener(gb,"gid_changed",c)}var Bb=_.H.addListener(D,"tilesloading_changed",function(){D.get("tilesloading")&&(Bb.remove(),fb())});_.H.addListenerOnce(D,"tilesloaded",function(){_.L("util",function(b){b.R.j();window.setTimeout((0,_.u)(b.j.S,
b.j),5E3);b.U(a)})});_.em(a,"Mm");b.v2&&_.em(a,"Mz");_.gm("Mm","-p",a,!(!a||!a.Ka));GA(a,F);_.jm(a,"Mm");_.ul(function(){_.jm(a,"Mm")});FA(a);n&&PA(new QA(n),a,function(){return 0!=a.get("draggable")})}EA(a);var xc=Az(_.Di()),n=new dB(zz(),a,new hA(z,function(a){return a||xc}));MA(n,a.overlayMapTypes);DA(a,p.U.mapPane);_.T[35]&&k.bindTo("card",a);b.Ka||OA(a);d&&window.setTimeout(function(){_.H.trigger(a,"projection_changed");_.sa(a.get("bounds"))&&_.H.trigger(a,"bounds_changed");_.H.trigger(a,"tilt_changed");
_.sa(a.get("heading"))&&_.H.trigger(a,"heading_changed")},0);_.T[15]&&(d=_.Fv(_.Gv()),d=new KA(d[0],z),d.bindTo("mapType",F),d.bindTo("center",a),d.bindTo("zoom",k),a.getPrintableImageUri=(0,_.u)(d.getPrintableImageUri,d),a.setFpsMeasurementCallback=(0,_.u)(D.setFpsMeasurementCallback,D),k.bindTo("authUser",a),a.bindTo("tilesloading",D))};
jB.prototype.fitBounds=function(a,b){function c(){var c=_.vf(a.getDiv());c.width-=80;c.width=Math.max(1,c.width);c.height-=80;c.height=Math.max(1,c.height);var e=a.getProjection(),f=b.getSouthWest(),g=b.getNorthEast(),h=f.lng(),k=g.lng();h>k&&(f=new _.K(f.lat(),h-360,!0));f=e.fromLatLngToPoint(f);h=e.fromLatLngToPoint(g);g=Math.max(f.x,h.x)-Math.min(f.x,h.x);f=Math.max(f.y,h.y)-Math.min(f.y,h.y);c=g>c.width||f>c.height?0:Math.floor(Math.min(_.ek(c.width+1E-12)-_.ek(g+1E-12),_.ek(c.height+1E-12)-_.ek(f+
1E-12)));g=_.Rj(e,b,0);e=_.Sj(e,new _.M((g.ya+g.Ca)/2,(g.wa+g.Da)/2),0);_.E(c)&&(a.setCenter(e),a.setZoom(c))}a.getProjection()?c():_.H.addListenerOnce(a,"projection_changed",c)};jB.prototype.j=function(a,b,c,d,e,f){var g=_.Jv(a,b,c,d,{ad:f});_.yk(function(){g.setUrl(e)});return g};_.kc("map",new jB);});
